name: ecomerce_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  dio: ^5.4.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  riverpod: ^2.5.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.7
  fpdart: ^1.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
